### ISSUE TITLE
Installing Fast-AI

### ISSUE THREAD

**Issue by Quickflash777** [DisQS/ML-Anderson3D#15]
pip install fastai==1.0.61

**Comment by RudoRoemer** [comment]
For me, the command

pip install --user fastai==1.0.61

leads to an error

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_cjgy3ws/spacy/

Any ideas?

**Comment by Quickflash777** [comment]
Try pip3 install --upgrade pip or pip install --upgrade setuptools. The problem is likely that your pip is in an old version (at least according to my web search)

**Comment by RudoRoemer** [comment]
pip3 install --user --upgrade pip did the pip-update trick.

**Comment by RudoRoemer** [comment]
Then 

pip install --user fastai==1.0.61

completed, but only after a long time.
